'use client';
import Link from 'next/link';
import { Post } from '@/lib/posts';
import { format } from 'date-fns';

export default function PostCard({
  post,
  index = 0,
  basePath = '/blog',
}: {
  post: Post;
  index?: number;
  basePath?: string;
}) {
  return (
    <Link href={`${basePath}/${post.slug}`} style={{ textDecoration: 'none' }}>
      <article
        className={`animate-fade-up delay-${Math.min(index + 1, 4)} comic-card`}
        style={{
          background:   'var(--warm-white)',
          borderRadius: '8px',
          padding:      '1.3rem 1.5rem',
          display:      'flex',
          gap:          '1rem',
          alignItems:   'flex-start',
          cursor:       'pointer',
        }}
      >
        {/* Left accent stripe */}
        <div style={{
          width:        '3px',
          alignSelf:    'stretch',
          borderRadius: '3px',
          background:   'linear-gradient(180deg, var(--vermilion) 0%, var(--gold) 100%)',
          flexShrink:   0,
        }} />

        {/* Content */}
        <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: '0.45rem' }}>
          <div style={{
            display: 'flex', alignItems: 'center', gap: '0.5rem',
            fontSize: '0.73rem', color: 'var(--text-muted)', fontWeight: 500,
          }}>
            <span>{format(new Date(post.date), 'd MMM yyyy')}</span>
            <span style={{ opacity: 0.4 }}>·</span>
            <span>{post.readingTime}</span>
            {post.autoGenerated && (
              <>
                <span style={{ opacity: 0.4 }}>·</span>
                <span style={{
                  fontSize: '0.63rem', fontWeight: 700, letterSpacing: '0.04em',
                  color: 'var(--jade)', background: 'rgba(30,122,82,0.08)',
                  border: '1px solid rgba(30,122,82,0.2)',
                  padding: '0.1em 0.5em', borderRadius: '4px',
                  textTransform: 'uppercase',
                }}>AI</span>
              </>
            )}
          </div>

          <h2 style={{
            fontFamily: "'Lora', serif",
            fontSize:   '1.05rem',
            fontWeight: 700,
            color:      'var(--brown-dark)',
            lineHeight: 1.35,
            margin:     0,
          }}>
            {post.title}
          </h2>

          <p style={{
            color:           'var(--text-secondary)',
            fontSize:        '0.85rem',
            lineHeight:      1.65,
            margin:          0,
            overflow:        'hidden',
            display:         '-webkit-box',
            WebkitLineClamp: 2,
            WebkitBoxOrient: 'vertical',
          }}>
            {post.excerpt}
          </p>

          {post.tags.length > 0 && (
            <div style={{ display: 'flex', gap: '0.35rem', flexWrap: 'wrap', paddingTop: '0.1rem' }}>
              {post.tags.slice(0, 4).map(tag => (
                <span key={tag} className="tag" style={{ fontSize: '0.68rem' }}>{tag}</span>
              ))}
            </div>
          )}
        </div>

        {/* Arrow cue */}
        <div style={{
          flexShrink: 0, color: 'var(--vermilion)',
          fontSize: '1rem', fontWeight: 700,
          paddingTop: '0.15rem', opacity: 0.45,
        }}>→</div>
      </article>
    </Link>
  );
}
