export interface LearnChannel {
  id:          string;
  channelId:   string;
  name:        string;
  handle:      string;
  description: string;
  focus:       string[];
  emoji:       string;
}

export const LEARN_CHANNELS: LearnChannel[] = [
  {
    id:          'ibm',
    channelId:   'UCKWaEZ-_VweaEx1j62do_vQ',
    name:        'IBM Technology',
    handle:      '@IBMTechnology',
    description: 'Cloud, AI, DevOps, and enterprise architecture explained clearly.',
    focus:       ['Cloud', 'AI', 'DevOps', 'Enterprise'],
    emoji:       '🔵',
  },
  {
    id:          'fireship',
    channelId:   'UCsBjURrPoezykLs9EqgamOA',
    name:        'Fireship',
    handle:      '@Fireship',
    description: 'Fast, practical explainers on modern web development.',
    focus:       ['Web Dev', 'TypeScript', 'React'],
    emoji:       '🔥',
  },
  {
    id:          'bytebytego',
    channelId:   'UCZgt6AzoyjslHTC9dz0UoTw',
    name:        'ByteByteGo',
    handle:      '@ByteByteGo',
    description: 'System design concepts essential for senior interviews.',
    focus:       ['System Design', 'Architecture', 'Scale'],
    emoji:       '⚙️',
  },
  {
    id:          'techworld',
    channelId:   'UCdngmbVKX1Tgre699-XLlUA',
    name:        'TechWorld with Nana',
    handle:      '@TechWorldwithNana',
    description: 'Kubernetes, Docker, CI/CD, and cloud-native from scratch.',
    focus:       ['Kubernetes', 'Docker', 'CI/CD'],
    emoji:       '🚢',
  },
  {
    id:          'theo',
    channelId:   'UCbRP3c757lWg9M-U7TyEkXA',
    name:        'Theo — t3.gg',
    handle:      '@t3dotgg',
    description: 'TypeScript, React, and the modern full-stack web ecosystem.',
    focus:       ['TypeScript', 'React', 'Next.js'],
    emoji:       '💜',
  },
  {
    id:          'hussein',
    channelId:   'UC_ML5xP23TOWKUcc-oAE_Eg',
    name:        'Hussein Nasser',
    handle:      '@hnasr',
    description: 'Backend engineering, networking, databases, and protocols.',
    focus:       ['Backend', 'Networking', 'Databases'],
    emoji:       '🌐',
  },
  {
    id:          'techwithTim',
    channelId:   'UC4JX40jDee_tINbkjycV4Sg',
    name:        'Tech With Tim',
    handle:      '@TechWithTim',
    description: 'Python, machine learning, and game development tutorials.',
    focus:       ['Python', 'ML', 'Algorithms'],
    emoji:       '🐍',
  },
  {
    id:          'tinaHuang',
    channelId:   'UC2UXDak6o7rBm23k3Vv5dww',
    name:        'Tina Huang',
    handle:      '@TinaHuang1',
    description: 'Data science, AI engineering, and career advice from ex-Meta.',
    focus:       ['Data Science', 'AI', 'Career'],
    emoji:       '📊',
  },
  {
    id:          'traversy',
    channelId:   'UC29ju8bIPH5as8OGnQzwJyA',
    name:        'Traversy Media',
    handle:      '@TraversyMedia',
    description: 'Full-stack web development crash courses and project builds.',
    focus:       ['Web Dev', 'JavaScript', 'Full Stack'],
    emoji:       '💻',
  },
  {
    id:          'networkchuck',
    channelId:   'UC9x0AN7BWHpCDHSm9NiJFJQ',
    name:        'NetworkChuck',
    handle:      '@NetworkChuck',
    description: 'Networking, Linux, cloud, and cybersecurity with energy.',
    focus:       ['Networking', 'Linux', 'Cloud', 'Security'],
    emoji:       '☕',
  },
  {
    id:          'googledev',
    channelId:   'UC_x5XG1OV2P6uZZ5FSM9Ttw',
    name:        'Google for Developers',
    handle:      '@GoogleDevelopers',
    description: 'Official Google dev channel — Gemini, Flutter, Firebase, GCP.',
    focus:       ['Google Cloud', 'Flutter', 'AI', 'Firebase'],
    emoji:       '🟡',
  },
  {
    id:          'indently',
    channelId:   'UCuudpdbKmQWq2PPzYgVCWlA',
    name:        'Indently',
    handle:      '@Indently',
    description: 'Clean, concise Python tutorials from basics to advanced patterns.',
    focus:       ['Python', 'OOP', 'Best Practices'],
    emoji:       '🎯',
  },
  {
    id:          'dreamsofcode',
    channelId:   'UCWQaM7SpSECp9FELz-cHzuQ',
    name:        'Dreams of Code',
    handle:      '@dreamsofcode',
    description: 'Go, Rust, and terminal tooling — practical systems programming.',
    focus:       ['Go', 'Rust', 'Systems', 'CLI'],
    emoji:       '🦀',
  },
  {
    id:          'primeTime',
    channelId:   'UCUyeluBRhGPCW4rPe_UvBZQ',
    name:        'ThePrimeTime',
    handle:      '@ThePrimeTimeagen',
    description: 'ThePrimeagen reacts to tech drama, articles, and hot takes.',
    focus:       ['Tech Opinions', 'Rust', 'Neovim'],
    emoji:       '⚡',
  },
  {
    id:          'lowlevel',
    channelId:   'UC6biysICWOJ-C3P4Tyeggzg',
    name:        'Low Level',
    handle:      '@LowLevelTV',
    description: 'C, Rust, assembly, and computer security from the ground up.',
    focus:       ['C', 'Assembly', 'Security', 'Systems'],
    emoji:       '🔧',
  },
  {
    id:          'thecodingsloth',
    channelId:   'UCxVPH8W2ayMey1-b0SY8rBQ',
    name:        'The Coding Sloth',
    handle:      '@TheCodingSloth',
    description: 'Relaxed, practical programming tutorials with real project focus.',
    focus:       ['Python', 'Web Dev', 'Projects'],
    emoji:       '🦥',
  },
  {
    id:          'nateherk',
    channelId:   'UC2ojq-nuP8ceeHqiroeKhBA',
    name:        'Nate Herk',
    handle:      '@nateherk',
    description: 'AI automation and n8n workflows — building agents without code.',
    focus:       ['AI Agents', 'Automation', 'n8n'],
    emoji:       '🤖',
  },
  {
    id:          'anthropic',
    channelId:   'UCrDwWp7EBBv4NwvScIpBDOA',
    name:        'Anthropic',
    handle:      '@anthropic-ai',
    description: 'Official Anthropic channel — Claude, AI safety, and research.',
    focus:       ['Claude', 'AI Safety', 'LLMs'],
    emoji:       '🧠',
  },
  {
    id:          'webdevsimplified',
    channelId:   'UCFbNIlppjAuEX4znoulh0Cw',
    name:        'Web Dev Simplified',
    handle:      '@WebDevSimplified',
    description: 'Modern web development explained simply — React, JS, CSS, full-stack.',
    focus:       ['React', 'JavaScript', 'CSS', 'Full Stack'],
    emoji:       '🎓',
  },
  {
    id:          'bootdotdev',
    channelId:   'UC9HOZ53gnHP3f_b-wixS74g',
    name:        'Boot.dev',
    handle:      '@bootdotdev',
    description: 'Backend development fundamentals — Python, Go, algorithms, and CS concepts.',
    focus:       ['Backend', 'Python', 'Go', 'Algorithms'],
    emoji:       '🚀',
  },
];
