import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import readingTime from 'reading-time';

const postsDir   = path.resolve(process.cwd(), 'content/posts');
const digestsDir = path.resolve(process.cwd(), 'content/digests');
const githotDir  = path.resolve(process.cwd(), 'content/githot');

export interface Post {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  tags: string[];
  readingTime: string;
  content: string;
  coverEmoji?: string;
  autoGenerated?: boolean;
}

/** Reject slugs that contain path traversal sequences or invalid characters. */
function isSafeSlug(slug: string): boolean {
  return /^[a-zA-Z0-9._-]+$/.test(slug) && !slug.includes('..');
}

/** Confirm the resolved file path stays inside the expected directory. */
function isInsideDir(dir: string, filePath: string): boolean {
  const relative = path.relative(dir, filePath);
  return !relative.startsWith('..') && !path.isAbsolute(relative);
}

function readDir(dir: string, defaultEmoji = '🤖'): Post[] {
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.mdx') || f.endsWith('.md'));
  return files
    .map(file => {
      const slug = file.replace(/\.(mdx|md)$/, '');
      const raw = fs.readFileSync(path.join(dir, file), 'utf8');
      const { data, content } = matter(raw);
      return {
        slug,
        title:       data.title || 'Untitled',
        date:        data.date || new Date().toISOString(),
        excerpt:     data.excerpt || '',
        tags:        data.tags || [],
        coverEmoji:     data.coverEmoji || defaultEmoji,
        autoGenerated:  data.auto_generated === true,
        readingTime:    readingTime(content).text,
        content,
      };
    })
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

function getBySlug(dir: string, slug: string, defaultEmoji = '🤖'): Post | null {
  if (!isSafeSlug(slug)) return null;

  const mdxPath = path.join(dir, `${slug}.mdx`);
  const mdPath  = path.join(dir, `${slug}.md`);
  const target  = fs.existsSync(mdxPath) ? mdxPath : fs.existsSync(mdPath) ? mdPath : null;

  if (!target || !isInsideDir(dir, target)) return null;

  const raw = fs.readFileSync(target, 'utf8');
  const { data, content } = matter(raw);
  return {
    slug,
    title:       data.title || 'Untitled',
    date:        data.date || new Date().toISOString(),
    excerpt:     data.excerpt || '',
    tags:        data.tags || [],
    coverEmoji:  data.coverEmoji || defaultEmoji,
    readingTime: readingTime(content).text,
    content,
  };
}

export function getAllPosts():             Post[]      { return readDir(postsDir, '✍️'); }
export function getPostBySlug(slug: string): Post | null { return getBySlug(postsDir, slug, '✍️'); }

export function getAllDigests():               Post[]      { return readDir(digestsDir, '🤖'); }
export function getDigestBySlug(slug: string): Post | null { return getBySlug(digestsDir, slug, '🤖'); }

export function getAllGithot():               Post[]      { return readDir(githotDir, '🔥'); }
export function getGithotBySlug(slug: string): Post | null { return getBySlug(githotDir, slug, '🔥'); }

export function getAllTags(): string[] {
  const tags = new Set<string>();
  getAllPosts().forEach(p => p.tags.forEach(t => tags.add(t)));
  return Array.from(tags);
}
