import fs from 'fs';
import path from 'path';
import type { DigestEntry } from './summarize';

function formatDate(date: Date): string {
  return date.toISOString().split('T')[0];
}

function entryToMdx(entry: DigestEntry, index: number): string {
  const heading = `## ${index + 1}. [${entry.title}](${entry.link})`;
  const source = `**Source:** ${entry.source}`;
  const summary = entry.summary;
  const takeaways = entry.keyTakeaways.map(t => `- ${t}`).join('\n');

  const diagram = entry.diagram
    ? `\n### Concept Diagram\n\n\`\`\`mermaid\n${entry.diagram}\n\`\`\`\n`
    : '';

  return `${heading}\n\n${source}\n\n${summary}\n\n**Key Takeaways:**\n${takeaways}\n${diagram}`;
}

export function generateDigestPost(entries: DigestEntry[], date = new Date()): string {
  const dateStr = formatDate(date);
  const sources = [...new Set(entries.map(e => e.source))].join(', ');

  const frontmatter = `---
title: "AI & Dev Digest — ${dateStr}"
date: "${dateStr}"
excerpt: "Weekly roundup of the latest from ${sources}. ${entries.length} items summarized."
tags: ["AI Digest", "Research", "Weekly"]
coverEmoji: "🤖"
auto_generated: true
---

> This digest was automatically generated by fetching the latest posts from ${sources} and summarizing them with Claude.

`;

  const body = entries.map((e, i) => entryToMdx(e, i)).join('\n\n---\n\n');

  return frontmatter + body + '\n';
}

export function writeDigestPost(entries: DigestEntry[], date = new Date()): string {
  const dateStr = formatDate(date);
  const dir = path.join(process.cwd(), 'content', 'digests');

  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const filePath = path.join(dir, `${dateStr}.mdx`);
  const content = generateDigestPost(entries, date);
  fs.writeFileSync(filePath, content, 'utf8');

  console.log(`\n📝 Post written to: content/digests/${dateStr}.mdx`);
  return filePath;
}
